name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello World
      run: echo "Hello world"

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc

    - name: Ensure test script is executable
      run: chmod +x runtests.sh

    - name: Build giftcardreader
      run: |
        echo "Building giftcardreader executables..."
        make clean
        make
        echo "Build completed."
        ls -la giftcardreader.* || echo "Warning: Some executables may be missing"

    - name: Run test suite
      continue-on-error: true
      run: |
        echo "============================="
        echo "Running gift card reader tests"
        echo "============================="
        ./runtests.sh
        echo "============================="
        echo "Test execution completed"
        echo "============================="

    - name: Display test summary
      if: always()
      run: |
        echo "Test run completed. Check the output above for detailed results."
        echo "Note: Test failures are expected during development."